### ISSUE TITLE
Does this also work with the IM-350 from "Wiener Netze"?

### ISSUE THREAD

**Issue by coolduke666** [bernikr/esphome-wienernetze-im150-smartmeter#1]
thx!

**Comment by bernikr** [comment]
I'm actually not sure, but feel free to test it out and report your results here.

From a little bit of research it should probably work, since the IM-350 doesn't report the values per phase but just the totals, which are hopefully in the same format as the IM-150.

**Comment by bernikr** [comment]
I've adapted the code now to work with more smartmeters. It is tested with the IM150 and IM151, but should also work with the IM350 now. I would appreciate feedback if it really works, as I have no IM250 to test it with.

**Comment by coolduke666** [comment]
I can confirm that it work with the IM350 as well... thx

**Comment by bernikr** [comment]
Thanks for the feedback
